### ISSUE TITLE
Should `register` batches be constrained to a single trait set

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#1015]
## What
Determine if the requirement for all elements of a batch `register` call (incl `preflight`) have the same trait set (a.k.a "batches are only ever one type of asset") should be relaxed.

## Why

We largely "guessed" that this constraint would make it easier for a manager to feasibly batch any given API call to it's back-end. It removes the need for the manager to determine if all the trait sets are the same. 

This may be overly restrictive in the case where a host legitimately wishes to publish several entities with different traits, as it forces each of these to make individual APi calls. As such, the manager has no opportunity to batch the back-end requests even if it could do so, as they are discrete API calls.

## Acceptance Criteria

 - Determine if we should relax this restriction.

**Comment by antirotor** [comment]
It really depends on the point, where you actually call `register`. Let me descibe how it works in our case now:

For publishing, we are using [pyblish-base](https://github.com/pyblish/pyblish-base).

So lets say you want to publish something complex, like camera track. In that case you will be publishing camera as alembic, camera as fbx, proxy geometry, image sequence (playblast of the camera movement), stmap for lens distortion and lets add something lens distortion informations as json file (because why not). Scene will then have these publish instances:

**Camera** - .fbx, .abc
**Model** - .abc
**Lens Distortion** - .exr (for stmap), .json for metadata.

Since stmap and metadata in json can be time based (lens distortion can change over time), they are actually sequence. Depending on Traits definitions all can have different Traits :)

Once you run publish, you can produce the data sequentially, because in most DCCs you are limited to main thread, GIL locks and what not. Pyblish uses bunch of little plugins that are run in phases - Collection phase, Validation, Extraction and Integration. Preflight in this case would run at the and of collection phase - but in this moment, publishing can be stopped by validations. Validations themselves are simple and out of the scope, Extraction phase can't run in batch because of those thread limitations and then you have Integration phase, where at the and `register()` should run and it can run on everything no matter of traits because at that moment everything is already determined and integration job is to move files to final destination and register new version in database (and so on).

Now within our API, there is no way to create multiple versions using one call, so performace-wise it doesn't really matter that much if you call `register()` over and over because the bottleneck then will be the API call to create version.

But if we create API end-point to do it in batch, you would still define every individual type of data fully - with all related traits. Long story short, I don't think that the constrain to single trait set can help here and it would be better to not have it.

Sorry about such long shout, but I wanted to have it a little bit of context.

**Comment by foundrytom** [comment]
Many thanks @antirotor - thats really helpful context. It'd be great to work through these publishing flows with you in more detail at some point!

**Comment by foundrytom** [comment]
Constraint removed as part of #1028
