### ISSUE TITLE
API: Remove the 'k' prefix from enum values

### ISSUE THREAD

**Issue by lpapp-foundry** [OpenAssetIO/OpenAssetIO#1064]
- enum class Access { kRead, kReadMultiple, kWrite, kWriteMultiple, kUnknown };
+ enum class Access { Read, ReadMultiple, Write, WriteMultiple, Unknown };

Rationale:

1. In my opinion, any C++ programmer would know that enums are "constant", so it does not have to be explicit.
2. Currently, it causes more typing than the proposed alternative.
3. For some engineers, like me, 'k' is a bit baffling to mean **c**onstant.
4. It is good habit in general, in my view, to start enum values with uppercase letter. I naturally start typing enum values with uppercase letters. Removing the 'k' would restore that.
5. If it is meant for some kind of scoping, enum classes from C++11 have already been scoped.

Please refer to an example here: https://en.wikipedia.org/wiki/C%2B%2B11#Strongly_typed_enumerations

I would probably also apply the same to Retention, Severity, etc.

It is a breaking change, but in my opinion worth it in the long-term.

**Comment by feltech** [comment]
For background, the current style is based on the [google style guide](https://google.github.io/styleguide/cppguide.html#Enumerator_Names), which we decided early on in the project to adopt more-or-less wholesale, to avoid arguments over naming scheme etc.

But I'm happy to change if there is a consensus that the current style is non-intuitive.

**Comment by lpapp-foundry** [comment]
Personally, I find Google's decision on this non-intuitive and uncommon.

**Comment by foundrytom** [comment]
There is an additional reason for the prefix. OpenAssetIO is bound to languages other than C++, which don't have strong typing systems or compilation stages (eg: Python). The prefix serves to make the constants more apparent in these situations, where you don't have a compiler or readily available introspection to fill in the gaps for you. 

We also try and make the API surface are as similar as possible between each of the languages we do support for two reasons.
 -  Firstly, to make it easier for developers working across multiple languages simultaneously (eg C++/Python as is the case in VFX). 
 - Secondly, to help get maximum usage out of the limited documentation resource we have, because examples can more easily be ported between languages. 
 
As such, though the prefix is not strictly necessary in C++ we keep the names consistent in other languages, and so we keep it in C++ too. 

Regardless of the consistency topic, sadly, any convention we do pick tends to work for some people and not for others. We democratically voted on which style guide to adopt some time ago, on the basis of "lets just pick one, well established, off-the-shelf style", then at least we can all agree together that we don't like it, and it's not directly associated with any one person historically. The Google standard won out there, and so that is the one we use on the project.

This change would need to go far beyond just Enums, if we did change it, as we use the `k` prefix for all constants, and so the scope is somewhat larger than it may first appear.

**Comment by foundrytom** [comment]
@lpapp-foundry your issue highlighted a good point - that we hadn't documented the reasoning behind the current state of the code base. We've since added these two DRs, that hopefully at least explain the background and motivations:

- https://github.com/OpenAssetIO/OpenAssetIO/blob/main/doc/decisions/DR020-Coding-style.md
- https://github.com/OpenAssetIO/OpenAssetIO/blob/main/doc/decisions/DR021-Cross-language-consistency.md

How would you like to proceed with this issue? In order to make a change, we'd need to get it approved by the TSC, so we'd need to demonstrate the relative value of any updated standard vs the associated costs to the group, ideally supported by a community consensus.

**Comment by foundrytom** [comment]
Closing after off-line discussion.
