### ISSUE TITLE
C++ Manager Plugin for Testing

### ISSUE THREAD

**Issue by SamCrooksFoundry** [OpenAssetIO/OpenAssetIO#1324]
## What

We want to build a simple C++ manager plugin to be used for testing the C++ manager system.

## Acceptance Criteria

* A manager plugin inside the OpenAssetIO examples directory. 
* It should only do the required capabilities and resolve.
* Entity references it resolves are hard coded, we have BAL as a mock.
* Independently buildable, not linked to OpenAssetIO's build system, but there should be CI/CTest tests to make sure it builds and runs.
* Link from README "quick start" section.

## Out of Scope

Not packaged and published, to build it, you'll need to pull the OpenAssetIO repository.

**Comment by feltech** [comment]
Whilst developing this we discovered that the PyPI build of OpenAssetIO _cannot_ load C++ manager plugins.

This is because the PyPI build uses a single shared library (the Python extension module) with the core C++ library baked into it as a static library.

This causes two problems:
* Our build system setup is designed to block all symbols from being exported except for those explicitly made visible. This means the Python extension module hides the symbols from the "foreign" C++ core library, so there are no symbols for a C++ manager plugin to link to.
* Python extension modules are loaded by the Python interpreter using `RTLD_LOCAL` (on POSIX), which prevents symbols from "leaking" between binaries, so even if our Python extension module exposes the necessary symbols, they will be "blocked" from other shared libraries.

The first problem could be solved by refactoring our build system to allow the `libopenassetio.a` library's symbols to be exported from the `_openassetio.so` Python extension module. This means 
* No longer having CMake generate an `export.h` header (`generate_export_header()`), since the generated export header for a static library is just a stub without any visibility flags. Instead, we would have to roll our own that works for both static and shared libraries and across platforms (lots of other projects do this).
* Ensure we use `$<LINK_LIBRARY:WHOLE_ARCHIVE,openassetio-core>`, so that _all_ symbols, not just those used by the Python extension module, are exported from the static library.
* Somehow exclude the core C++ library from the `--exclude-libs,ALL` linker argument, probably requiring us to eschew `ALL` and instead provide an explicit list of what libraries to exclude.

The second problem is more serious, though easier to "fix".
* We would have to (temporarily) override the flags using `sys.setdlopenflags(os.RTLD_GLOBAL | os.RTLD_LAZY)`. Though of course that's POSIX only.
* However, the [Python docs](https://docs.python.org/3/extending/extending.html) say 
  > Portability therefore requires not to make any assumptions about symbol visibility. This means that all symbols in extension modules should be declared static, except for the module’s initialization function, in order to avoid name clashes with other extension modules [...] And it means that symbols that should be accessible from other extension modules must be exported in a different way.

That last point especially means that the _correct_ solution would be to split the Python extension module and the core C++ (shared) library, so that the extension module can depend on the shared library, as can plugins.

Note that all the above applies to POSIX. Windows is another story and would need alternative fixes, if any are even possible (not explored in my investigations).

In the past, separating the core C++ library and the Python extension module in the PyPI package caused problems with linker search paths.  On Linux we have `RPATH` and on macOS we have `@loader_path`, but on Windows we have nothing. Fixing this will take further experimentation/consultation.
