### ISSUE TITLE
Finalize "pod" types/Aliases supported in key/value structures

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#142]
## What

We need to finalise the definitive list of value types supported in maps (`Specification`, `.info()`, Attributes). And provide programatic methods to determine the supported types in python, C++ and C.

**Comment by foundrytom** [comment]
@feltech think we're effectively doing this as part of #250?

**Comment by feltech** [comment]
> @feltech think we're effectively doing this as part of #250?

Yeah but by railroading it without much consideration. It's easy enough to change later. So would be good to make the decision properly rather than ad-hoc.

E.g. 
* Names of typedefs exposed in the public API - I just made these up, but if they're publicly visible we should have some consensus.
* `float` vs `double`, `int` vs `long`.

**Comment by elliotcmorris** [comment]
Closing due to age, we're happy with this as it stands and will revisit if it comes up.
