### ISSUE TITLE
[Investigation] Identify main time sinks in CI checks

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#602]
## What

Determine where the time is going in the various CI checks in order to define next steps to optimize build/test times. This could include experimental implementation of various tricks/improvements.

See #484 

## ACs

- Summary of where the time is going and what we can do!
- Issues for specific Tasks added to #484 
- PRs for low-hanging fruit fixed during investigation.

Time boxed to: 2 days

**Comment by feltech** [comment]
Looking at [this recent run](https://github.com/OpenAssetIO/OpenAssetIO/runs/8205542088) (for #601) the "Code quality / C++ linters" and "Code quality / Sanitizers (pull_request)" actions are both bottlenecks, taking 9 mins in total. Most of this time (more than 8 mins) is spent in the "Build and lint" step.

The difference between the two is the CMake preset used - "lint" vs. "sanitize".  The "lint" preset differs in that it enables cpplint, clang-idy, and clang-format.  The "sanitize" preset differs in that it enables ASan and UBsan and runs tests.

The "Tests / ubuntu-20.04" action also builds and runs tests, but took 4 mins.  So linting and sanitizers coincidentally take a similar amount of time (5 mins).

From this we can conclude a rough top three bottlenecks
* Executing tests with sanitizers enabled
* C++ linting during a build
* Building

The last one of course affects both actions.

**Comment by feltech** [comment]
Quick dirty timings of a local build, testing some low-hanging fruit in the form of build flags:

* Vanilla "lint" preset: 6m20.159s
* With `O0` and no LTO: 6m5.330s
* With `j2`: 3m33.346s

So optimisation flags have little impact on build times, especially when compared to the effect of a parallel build. 

[Github runners](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources) give us 2 cores for Ubuntu and Windows and 3 for MacOS.  So parallel builds are a no-brainer.

**Comment by feltech** [comment]
The common "Install dependencies" step on CI, i.e. our OS bootstrap script, takes up to a minute and could be ripe for optimisation. Looking at the same run as above, choosing the quickest 44 sec example ("C++ Linters"), we have

- 26 sec apt update + install
- 10 sec pip install
- 6 sec conan install (cached)
- <1 sec update-alternatives
- 3 sec `--version` reports (2 secs for clang-tidy alone)

**Comment by feltech** [comment]
Parallelised the bootstrap script:
- `apt update` and `apt install` rolled into a single line and suffixed with `&` to run as a child process.
- Similarly suffixed `pip install` with `&`.
- Then `wait` before doing the conan install (since it needs both the apt step and the pip step to complete).

It seems to help, but timings are very noisy so it's difficult to be conclusive.  I.e.:

Parallel: 32s, 1m47s, 54s, 1m0s, 32s
Serial: 1m22s, 44s, 41s, 1m2s, 1m6s

**Comment by feltech** [comment]
Parallel build jobs for "C++ linters" check:

Unlike the local build case, Github CI does not give a near-linear speed-up when doing two parallel builds:

<num jobs>: <time>, ...
1: 5m55s
auto: 4m43s, 4m38s
2: 4m46s
4: 6m33s

Also tried removing optimisations with, which only saved a few seconds, similar to previous result (4m15s in this case). 

Additionally tried to build a static library, rather than shared, to see if the linker introduced much overhead. Unfortunately not much effect (4m28s)

**Comment by feltech** [comment]
### Unity build

This is interesting. CMake has a ["unity build"](https://cmake.org/cmake/help/latest/prop_tgt/UNITY_BUILD.html) feature, whereby it concatenates `.cpp` files into one or more files, resulting in shorter compilation times.

To make this work with our codebase needs a fair bit of work.  

But once (hackily) working the "C++ linters" build step took only 1m36 - more than 3x speed boost!

The caveats are non-trivial, though
- Since it concatenates files, locating any linter warnings in the original source is more difficult.
- Since it concatenates files, it is easy to have a symbol collision for symbols that are file scoped (only one such collision occurs in our codebase, at least).
- Since we're no longer compiling the original source files, but rather a set of generated files, the `.clang-tidy` config file search path is affected, since the search path is relative to the file being compiled. This almost works out on CI, since the generated file is under `${PROJECT_ROOT}/build/...` and `.clang-tidy` in under `${PROJECT_ROOT}`.  However, the C API override `.clang-tidy` is no longer picked up, since it is in `${PROJECT_ROOT}/src/...`, i.e. not an ancestor of the `build` directory.

**Comment by feltech** [comment]
### ccache

After far too much pain, I eventually discovered that `actions/cache` [is immutable](https://github.com/actions/cache/blob/main/workarounds.md#update-a-cache).  With that revelation aside, applying `ccache` reduces the "build" step for linting and sanitizers as follows:

Linters: 4m57s to 3m32s
Sanitizers: 5m54s to 3m5s

A much better result than [when used locally](https://github.com/OpenAssetIO/OpenAssetIO/issues/484#issuecomment-1198325962) and worth doing.

**Comment by foundrytom** [comment]
> Linters: 4m57s to 3m32s Sanitizers: 5m54s to 3m5s
> 
> A much better result than [when used locally](https://github.com/OpenAssetIO/OpenAssetIO/issues/484#issuecomment-1198325962) and worth doing.

🎉 🎉 🎉 🎉 nice one @feltech - good to see how much the difference is on a massively overworked VM vs locally.
