### ISSUE TITLE
[Investigation] Areas with insufficient test coverage for release

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#652]
## What

Determine any significant holes in test coverage of release PyPi or Conan Center packages, and plan any follow-up work.

Timebox: Half a day

## Notes:

- C/C++ headers
- C++ only tested through python
- CMake options

**Comment by feltech** [comment]
## Platforms

We currently only run tests against Ubuntu 20.04 and Windows MSVC 2019 (via Github CI runners), both with Python 3.9. 

macOS was disabled (#475) but can be re-enabled now the ConanCenter recipe has been fixed.

We test building against CentOS 7 using the ASWF CY22 Docker image, but do not run tests. We will need our own Docker image that bundles unit test dependencies to run C/C++ tests. We could at least run Python-only `pytest` tests without much extra effort, though.

We can matrix Python versions (especially once #660 is done) [Note that we [have discovered](https://github.com/foundrytom/OpenAssetIO/actions/runs/3311734599/jobs/5467541233#step:7:1395,) that running tests through ASan gives (hopefully) false positives on Python 3.7, so would need to pin sanitizer runs to a compatible Python version].

## CMake module

We have no testing of our CMake exported module (`lib/cmake/OpenAssetIO/OpenAssetioConfig.cmake`), for consumption as an external CMake package.

We should have tests that use the OpenAssetIO CMake package
```
find_package(OpenAssetIO)
target_link_libraries(some.test PRIVATE OpenAssetIO::openassetio-core)
```

### Public headers

C/C++ tests include headers from the source tree. We could be missing/misconfiguring headers in the install tree, making our package unusable, and we'd never know.

Current C++ tests don't make use of all headers.  We should at least add a simple test that `#include`s all headers where we expect them to be, and detect any compilation error.  

C bindings seem to have good coverage, since we don't rely on testing through the Python interface, but still need testing against the install tree rather than source tree.

### CMake as a sub-project

Some effort has gone into making OpenAssetIO theoretically work as a subproject (e.g. [`FetchContent`](https://cmake.org/cmake/help/latest/module/FetchContent.html) or git submodules) but this is untested.

Testing it would require creating a separate test application that consumes OpenAssetIO as a subproject, e.g.
```
add_subdirectory(openassetio)
target_link_libraries(some.test PRIVATE openassetio-core)
```

Note: there may be more dev work to do here, I'm not 100% sure on the etiquette of subproject structure. E.g. often projects explicitly declare `ALIAS` targets to look like a CMake package, e.g.

```
add_library(OpenAssetIO::openassetio-core ALIAS openassetio-core)
```
but we don't currently do that.

## CMake options

### Requires relatively minor additionaly work

  * `BUILD_SHARED_LIBS` - Run all tests against both static and shared lib builds.
  * `OPENASSETIO_ENABLE_C` - Run Python/C++ tests with C component disabled.
  * `OPENASSETIO_ENABLE_NEW_DTAGS` - Should probably test install tree with and without this (i.e. RUNPATH vs. RPATH) enabled.
  * `OPENASSETIO_ENABLE_PYTHON` - Run C/C++ tests with Python disabled
  * `OPENASSETIO_ENABLE_SANITIZER_THREAD` /  `OPENASSETIO_ENABLE_SANITIZER_MEMORY` - Cannot be used alongside ASan so is simply never enabled. Should run all tests with these enabled.  Leak sanitizer is apparently integrated into ASan, so is unnecessary.  Good overview: https://developers.redhat.com/blog/2021/05/05/memory-error-checking-in-c-and-c-comparing-sanitizers-and-valgrind

### Requires significant additional work

  * `OPENASSETIO_ENABLE_COVERAGE `- Report C/C++ coverage - also consider Python coverage
  * `OPENASSETIO_GLIBCXX_USE_CXX11_ABI` - Should test C++11 ABI toggle works (especially once we're looking at CY23). Would probably need new C++ tests.
  * `OPENASSETIO_PYTHON_VERSION` - Should test that we can prioritise Python version when there is more than one available.

**Comment by foundrytom** [comment]
Great investigation @feltech. On the CMake options - do you think we need to cover all of them, on all platforms? Just wondering how the CI matrix is going to end up looking.

**Comment by feltech** [comment]
I don't think we need to matrix all the CMake options against multiple platforms.  I'll update the comment with thoughts.

**Comment by feltech** [comment]
This was Done but not Closed
