### ISSUE TITLE
Conan Center publishing

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#654]
## What

As a user I wish to add OpenAssetIO to my dependent C++ project using `conan` to install from Conan Centre

## Why

Conan is a well-used c++ package manager, this will facilitate the development of C++ integrations/PoC.

## ACs

- OpenAssetIO is available via https://conan.io/center as a source-only project
- Static .vs. shared defined via an option
- Python version range 3.7+

## Out of scope

- Prebuilt binary distributions

## Notes

Needs some consideration around how conan center handles options etc... in relation to binary distributions.

See https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md

**Comment by feltech** [comment]
As part of building a Conan package, we may wish to conditionally build and run the tests, based on an environment variable (_not_ `options` since that changes the `package_id` - we have seen prior art that uses this pattern.

**Comment by foundry-markf** [comment]
A general note, Conan Center recipes are being migrating to be Conan 2 supported at the moment.

There is compatibility between 1.x and 2.0 recipes if you're following the bleeding edge of 1.x APIs, and you can build with both major versions, which generates _different_ package_ids for each build of the same recipe + options + settings. The different package_ids are intentional by the Conan devs, as a different algorithm is used under the hood.

What I'm trying to say here, is if you follow the latest and greatest Conan 1.x APIs, you should have a good chance of being Conan 2.0 compliant.

https://docs.conan.io/en/latest/conan_v2.html for migration info

**Comment by feltech** [comment]
We should make pybind11 a `requires` rather than `tool_requires`, otherwise other packages alongside ours in the same dependency graph won't be forced to use the same pybind11 version.  

The disadvantage is that pybind11 will always be installed, even if not needed (since it's only used at build time). This is hopefully addressed in Conan 2, which has a more configurable `requires`.

Note that `tool_requires` is [still available](https://docs.conan.io/en/latest/migrating_to_2.0/recipes.html#requirements) in Conan 2 as a "legacy" hook.

**Comment by feltech** [comment]
PR up in https://github.com/conan-io/conan-center-index/pull/15106

First attempt failed on their CI because we require a newer CMake version.  Adding `tool_requires("cmake` works, but we must pin a version of `openssl`, since there is a `cpython` and `cmake` packages depend on different versions, so we must explicitly choose one.  PR updated with fix, awaiting CI (re)build at time of writing.

**Comment by feltech** [comment]
The package is now in ConanCenter at alpha.9.  Closing this.
