### ISSUE TITLE
Find alternate DCO commit check

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#709]
## What

Find a replacement for the current DCO CI check process

Timeboxed to 1 day intially

## Why

```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: tim-actions/get-pr-commits, tim-actions/dco
```

This hasn't been update yet, and has known issues with longer PRs

## Notes

- There may be something built into GitHub now?
- We've previously hit issues with large numbers of commits and variable passing so a self-contained action would be preferred.

**Comment by JeanChristopheMorinPerso** [comment]
https://github.com/apps/dco is really nice and works quite nicely. It's what's used in the ASWF organization. GitHub are also working on a native DCO check if I'm not mistaken but I haven't heard any news about that recently.

**Comment by feltech** [comment]
I added the https://github.com/apps/dco app to my personal account and pushed a dummy PR: https://github.com/feltech/OpenAssetIO/pull/10 - looks good to me!

**Comment by feltech** [comment]
I can't add the DCO app to the OpenAssetIO org myself - I've "requested" it. Presumably @foundrytom will have to approve.

**Comment by feltech** [comment]
Added #731 to remove the current action once the app is approved.

The only other repo where we do DCO checks is otio-openassetio. 

So added https://github.com/OpenAssetIO/otio-openassetio/issues/11 to update that.

The app should apply to all repos in the org, which is cool.

Closing this now, since it was just an investigation and this looks like a great solution.  Thanks @JeanChristopheMorinPerso !
