### ISSUE TITLE
[Investigation] Tooling for tutori-docs

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#946]
## What

Determine potential alternatives to Markdown + fenced code blocks/Doxygen for simple examples/tutorials.

## Why

Documentation is currently in Doxygen for the OpenAssetIO core API, and Markdown for its supplied example code and all other projects.

We need to add extended documentation and examples to MediaCreation and TraitGen projects (as well as OpenAssetIO and others in the longer term). The current forms are not easily tested and rely on manual QA to ensure the supplied instructions work as described. In addition, Doxygen is quite opaque to readers in it's un-rendered form, and relies on explicit steps to render (compared to desktop app/GitHub native rendering of Markdown et. al).

## ACs

- Determine potential alternative approaches to providing onboarding and example documentation/tutorials for use in the up-coming additions to our projects, with consideration of:
  - Readability of un-rendered documentation
  - Availability of automated testing/execution tooling
  - Simplicity of authoring process
- Examples of potential solutions (using `simpleResolver` as a reference)

Timebox: 2 days

**Comment by elliotcmorris** [comment]
Been doing some minor investigation on this, with a focus towards jupyter notebooks in particular.

### Dynamic run
Good news is that via a pretty [trivial](https://jupyterbook.org/en/stable/publish/gh-pages.html) process rendered notebooks can be published directly as github pages. Bad news is that these notebooks are static, ie, they show the results of the run that was done when the publish happened, and don't have the ability to re-run code inline, which would have been cool.

If we wanted dynamic notebooks, the obvious and correct thing to do would be to host an maintain a [JupyterHub](https://github.com/jupyterhub/jupyterhub) server. I would love to do this I think it would create the best possible docs experience, however, I don't think we can justify the technical expense on this team size. Maybe there's Jupyter-hosting-as-a-service offerings out there? None presented themselves in my quick skim.

The default jupyter book provides the ability to download the page as a file, and there are many jupyter engines out there which this could be plugged into. This isn't to mention the vs-code on the web stuff which has incredible jupyter support. It's _plausible_ that we could, given time to research, construct links that launched an in-browser editor.

I'll now go through other concerns and benefits.
### Benefit - Better code rendering
Jupyter, being a technology built for it, has better code rendering than Markdown, whilst also being a full markdown renderer in its own right.

### Benefit - Compiled documentation
A biggie, as a notebook has a build step, we will be able to rig our process so we get errors when attempting to publish broken documentation. Obvious win. 

### Benefit - Ecosystem interaction
Because a notebook can have multiple libraries installed together, we will be able to easily show interaction between our different libraries, I am thinking specifically media-creation here. The danger of doing this now is that when a change in a downstream repo effects upstream examples we are left without a mechanism of being informed, but due to the above, we'd be able to know, so the risk of doing this becomes less.

### Drawback - Python focus
The jupyter ecosystem presumes python, which is what most of our docs are in already. However, there is a risk that if we take the easy path of configuring python (it's as easy as adding `openassetio` to a requirements file,) we will paint ourselves into a corner with C++ or other language documentation and examples.
Additional research needs to be done on C++ jupyter environments, I am optimistic that we could provide a base docker-image or codespace kernel which would allow C++ with minimal to zero config on the user side, but this is a task in itself to figure out. Requires more research.

### Drawback - Can't intermix with pages
As far as I can tell, you can't mix a jupyter based site with a markdown/jekyll based on. (This is a soft assertion though, I havn't looked much into it.)
If it's true that you can't, we become presented with the choice of separating a certain class of examples to a separate repo/site and linking to it, which is a less smooth experience, or porting all our existing docs to a jupyter format.
There's a high chance this is an offsettable problem, I haven't looked much into it.

**Comment by feltech** [comment]
Great write-up, I agree with thinking Jupyter is a no-brainer

> Additional research needs to be done on C++ jupyter environments

[xeus-cling](https://xeus-cling.readthedocs.io/en/latest/index.html) looks pretty mature.  You have to tell it where your include and library paths are, of course.

I haven't found an example that parametrises the include/library paths in order to make the notebook portable (e.g. environment variable interpolation) - all paths I've seen in examples/posts so far are absolute - but it may be possible.

Failing that, the providing a Docker image with everything installed to the system include/lib dirs could be a workaround.

There's also the complication that the only demo manager we have at the moment is in Python,  so it gets pretty meta (and possibly quite tricky) if we end up embedding a Python interpreter inside the C++ interpreter of a C++ notebook.

**Comment by foundrytom** [comment]
Found this: https://mybinder.org

**Comment by foundrytom** [comment]
Update: Preference is for some form of Jupyter based setup, that avoids having to check-in built documentation to the repo, that allows examples to be tested in CI.

**Comment by feltech** [comment]
Forgot to link this PR proving that C++ notebooks are doable, albeit with Conda virtual environments, rather than Python `venv`s, and limited to older Clang versions

- https://github.com/OpenAssetIO/OpenAssetIO/pull/1027

**Comment by feltech** [comment]
We've organically settled on Jupyter as our go-to solution for tutori-docs, with some even in `main`.
