### ISSUE TITLE
Fix resolve documentation

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#981]
## What

Ensure no documentation refers to the old "primary string" concept.

## Why

This was outmoded when we moved to traits.

It is still present in several sections of `ManagerInterface.hpp` and maybe others. (see Entity Reference Resolution section)

**Comment by feltech** [comment]
@foundrytom - just to double-check, this issue was auto-closed by #943. However, the issue description mentions "still present in several sections".  I did a quick grep for "primary string" and didn't see anything, so probably all good, but thought it was worth a double-check that this issue really should have been closed.

**Comment by foundrytom** [comment]
@feltech thanks for the due dil - I couldn't find any either - so relieved you came to the same conclusion :-)
