### ISSUE TITLE
Bump ASWF `ci-base` container to 20XX

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#984]
## What

https://academysoftwarefdn.slack.com/archives/C0169RX7MMK/p1687038668297979

Update the `openassetio-build` container to use VFX platform 2023 as a base and publish under a tag with the corresponding base container version. Update CI matrix to use 2022/2023.

## Why

Helps ensure compatibility with ref platform 2023.

## Notes

If this is done before https://github.com/OpenAssetIO/OpenAssetIO/issues/1094 then we can hopefully remove the version pinning of `actions/checkout` introduced in https://github.com/OpenAssetIO/OpenAssetIO-TraitGen/pull/47 and  https://github.com/OpenAssetIO/OpenAssetIO-Test-CMake/pull/12

**Comment by elliotcmorris** [comment]
V1.0.0 should have a solid idea of what the core VFX reference platform is for the project, which includes doing this.

**Comment by feltech** [comment]
This has become more urgent since https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/ [causing](https://github.com/OpenAssetIO/OpenAssetIO/actions/runs/9807282377/job/27080742052?pr=1342)
```
 /__e/node20/bin/node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /__e/node20/bin/node)
/__e/node20/bin/node: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /__e/node20/bin/node)
/__e/node20/bin/node: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /__e/node20/bin/node)
/__e/node20/bin/node: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /__e/node20/bin/node)
/__e/node20/bin/node: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /__e/node20/bin/node)
/__e/node20/bin/node: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /__e/node20/bin/node)
```

The [ASWF CY23 images](https://github.com/AcademySoftwareFoundation/aswf-docker/blob/master/CHANGELOG.md#new-ci-images-1) are based on Rocky 8.8 with GCC 11.2.1. This should be bug-for-bug compatible with RHEL 8.8.  There's a [table on DistroWatch](https://distrowatch.com/table.php?distribution=redhat) showing (at time of writing) RHEL 8.10, which lists glibc 2.28. It's remarkably difficult to track down this basic information :cry: .  So the obvious solution is to fire up a container and look inside...

```
$ docker run --rm -it aswf/ci-base:2023 bash
# gcc --version
gcc (GCC) 11.2.1 20220127 (Red Hat 11.2.1-9)
<snip>
```

libc:
```
# cat $(gcc --print-file-name libc.so)
<snip>
GROUP ( /lib64/libc.so.6 /usr/lib64/libc_nonshared.a  AS_NEEDED ( /lib64/ld-linux-x86-64.so.2 ) )
# /lib64/libc.so.6 --version
GNU C Library (GNU libc) stable release version 2.28.
```

libstdc++
```
# cat $(gcc --print-file-name libstdc++.so)
<snip>
INPUT ( /usr/lib64/libstdc++.so.6 -lstdc++_nonshared )
# strings /usr/lib64/libstdc++.so.6 | grep GLIBCXX
<snip>
GLIBCXX_3.4.20
GLIBCXX_3.4.21
<snip>
# strings /usr/lib64/libstdc++.so.6 | grep CXXABI
<snip>
CXXABI_1.3.9
<snip>
```

So everything being complained about is available in the ASWF CY23 Docker images.
